### PR TITLE
feat: link to current song directly

### PR DESCRIPTION
**Pull request by nekowinston**
Changes `getArtwork` to `getMetadata`, which uses the tools.applemediaservices.com API instead. This response contains a link to the queried song, which is meant for sharing on social media, etc.

Also changes behaviour where if metadata isn't available, the Discord buttons won't show at all, since the URL would be empty.

### CODE REVIEW

**Comment by nekowinston** [comment]
I also noticed that the fallback image doesn't appear?
image

It seems like the new AppID introduced in 908d5021d7d29f8961dda70a398ee5998394f852 doesn't have a resource named "applemusic", nor "play" for the small image.
https://github.com/caarlos0/discord-applemusic-rich-presence/blob/908d5021d7d29f8961dda70a398ee5998394f852/main.go#L294-L295

**Comment by caarlos0** [comment]
> I also noticed that the fallback image doesn't appear? image
> 
> It seems like the new AppID introduced in [908d502](https://github.com/caarlos0/discord-applemusic-rich-presence/commit/908d5021d7d29f8961dda70a398ee5998394f852) doesn't have a resource named "applemusic", nor "play" for the small image.
> 
> https://github.com/caarlos0/discord-applemusic-rich-presence/blob/908d5021d7d29f8961dda70a398ee5998394f852/main.go#L294-L295

ah, might be, will fix!

**Comment by caarlos0** [comment]
thanks for the pr! looks good!

**Comment by caarlos0** [comment]
> It seems like the new AppID introduced in [908d502](https://github.com/caarlos0/discord-applemusic-rich-presence/commit/908d5021d7d29f8961dda70a398ee5998394f852) doesn't have a resource named "applemusic", nor "play" for the small image.

should be fixed

**Comment by caarlos0** [comment]
actually, it never saves the images... will revert that commit ¯\_(ツ)_/¯

**Comment by nekowinston** [comment]
Hmm which images? I assumed you were talking about the album art, but then I noticed that you reverted the own App ID.

If you mean the Assets in RP, they have quite aggressive caching, but it does work. I recently updated my MPD fork to use my AppID as well, and it took a while for the images to process when deleting and uploading to rename.

**Comment by nekowinston** [comment]
Quickly following up on the topic of caching, wouldn't it be better if it used `artist album` instead of `artist album song` for the cache key?
https://github.com/caarlos0/discord-applemusic-rich-presence/blob/930eb8e649a679ac18b4fd33b17168a100094087/main.go#L218-L221

**Comment by caarlos0** [comment]
> Hmm which images? I assumed you were talking about the album art, but then I noticed that you reverted the own App ID.
> 
> If you mean the Assets in RP, they have quite aggressive caching, but it does work. I recently updated my MPD fork to use my AppID as well, and it took a while for the images to process when deleting and uploading to rename.

ahh, that might be it, will try again later and revert the revert if it works

**Comment by caarlos0** [comment]
> Quickly following up on the topic of caching, wouldn't it be better if it used `artist album` instead of `artist album song` for the cache key?
> 
> https://github.com/caarlos0/discord-applemusic-rich-presence/blob/930eb8e649a679ac18b4fd33b17168a100094087/main.go#L218-L221

when I tested it seemed to yell the same results, I leave the song too "just in case", as it doesn't seem to hurt

**Pull request merged**
